version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "${REGISTRY_PORT:-5000}:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ${REGISTRY_DATA_FOLDER}:/data